### ISSUE TITLE
missing file containing terrainshadergenerator

### ISSUE THREAD

**Issue by mjk8ball** [StephenLujan/Panda-3d-Procedural-Terrain-Engine#1]
console from running the source:

Hello World
DirectStart: Starting the game.
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    from terrain import *
  File "AnimateDream-Panda-3d-Procedural-Terrain-Engine-e2d005d\AnimateDream-Panda-3d-Procedural-Terrain-Engine-e2d005d\src\terrain.py", line 28, in <module>
    from terraintexturer import *
  File "AnimateDream-Panda-3d-Procedural-Terrain-Engine-e2d005d\AnimateDream-Panda-3d-Procedural-Terrain-Engine-e2d005d\src\terraintexturer.py", line 17, in <module>
    from terrainshadergenerator import *
ImportError: No module named terrainshadergenerator

terrainshadergenerator module (guessing) is home to the class TerrainShaderGenerator? looks like the file for that module wasn't included in the repository.

**Comment by StephenLujan** [comment]
Oh good grief. Somehow I missed uploading that file. I've lost data after a hard drive died and was counting on this project being up to date online. It looks like I have to rewrite my whole shader generator now. My new one terabyte external will be taking regular backups from now on.

**Comment by StephenLujan** [comment]
Resolved
