### ISSUE TITLE
AssertionError: glyph->_geom_count >= 0

### ISSUE THREAD

**Issue by ghost** [StephenLujan/Panda-3d-Procedural-Terrain-Engine#2]
This assertion is quite common. I experienced it popping up nearly instantly when scene is initialized at place seemingly underwater. Otherwise going to some direction for a bit also triggers it. Full console output as follows:

```
*(MainThread) config.py:25   running from:/c:/src/game/src
DirectStart: Starting the game.
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
*(MainThread) main.py:36   Hello World
*(MainThread) main.py:323  instancing world...
*(MainThread) main.py:325  calling run()...
:net(error): Unable to open TCP connection to server 127.0.0.1 on port 5185
:pstats(error): Couldn't connect to PStatServer at localhost:5185
*(MainThread) terrain.py:239  initializing heightmap...
*(MainThread) terrain.py:93   height normalized from [0.05445,0.88945]
*(MainThread) terrain.py:255  initializing terrain rendering properties...
*(MainThread) terraintexturer.py:32   initializing terrain texturer...
*(MainThread) terraintexturer.py:166  loading textures...
*(MainThread) terraintexturer.py:206  intializing terrain shader generator...
*(MainThread) terrainshadergenerator.py:33   setting basic terrain shader input...
*(MainThread) terrain.py:648  set shader input brightnessAdjust to 1.74173465998
*(MainThread) terrain.py:648  set shader input fogDensity to 0.0106638027692
*(MainThread) terrain.py:648  set shader input normalMapStrength to 1.6
*(MainThread) terrain.py:648  set shader input parallaxStrength to 0.01
*(MainThread) terrain.py:648  set shader input debugDisableDiffuse to 0
*(MainThread) terrain.py:648  set shader input detailHugeScale to 2.0
*(MainThread) terrain.py:648  set shader input detailBigScale to 14.0
*(MainThread) terrain.py:648  set shader input detailSmallScale to 58.1818181818
*(MainThread) terrain.py:648  set shader input ambientOcclusion to 1.0
*(MainThread) terrainshadergenerator.py:54   done
*(MainThread) terraintexturer.py:214  terrain shader generator initialized...
*(MainThread) terrainshadergenerator.py:417  loading terrain settings into shader input...
*(MainThread) terrainshadergenerator.py:420  assembling shader cg code
*(MainThread) terrain.py:271  rendering properties initialized...
*(MainThread) terrain.py:404  preloading terrain tiles...
*(MainThread) terrain.py:434  Loading Terrain 0/4
*(MainThread) terrain.py:568  tile generated at (-128, -128)
*(MainThread) terrain.py:434  Loading Terrain 1/4
*(MainThread) terrain.py:568  tile generated at (-128, 0)
*(MainThread) terrain.py:434  Loading Terrain 2/4
*(MainThread) terrain.py:568  tile generated at (0, -128)
*(MainThread) terrain.py:434  Loading Terrain 3/4
*(MainThread) terrain.py:568  tile generated at (0, 0)
*(MainThread) terrain.py:276  initializing terrain update task...
*(MainThread) main.py:82   terrain preloaded
*(MainThread) waterNode.py:28   setting up water plane at z=90.0
*(MainThread) terrain.py:239  initializing heightmap...
*(MainThread) terrain.py:614  Tile deleted from (0, 0)
*(MainThread) terrain.py:614  Tile deleted from (-128, 0)
*(MainThread) terrain.py:614  Tile deleted from (-128, -128)
*(MainThread) terrain.py:614  Tile deleted from (0, -128)
*(MainThread) terrain.py:93   height normalized from [0.05445,0.88945]
*(MainThread) terrain.py:568  tile generated at (0, 0)
*(MainThread) terrain.py:568  tile generated at (-128, 0)
*(MainThread) terrain.py:568  tile generated at (0, -128)
*(MainThread) terrain.py:568  tile generated at (-128, -128)
*(MainThread) terrain.py:568  tile generated at (-256, -128)
*(MainThread) terrain.py:568  tile generated at (-256, 0)
*(MainThread) terrain.py:607  Tile removed from (0, 0)
*(MainThread) terrain.py:568  tile generated at (-256, -256)
*(MainThread) terrain.py:568  tile generated at (-384, -128)
*(MainThread) terrain.py:607  Tile removed from (0, -128)
*(MainThread) terrain.py:568  tile generated at (-384, 0)
*(MainThread) terrain.py:568  tile generated at (-384, -256)
*(MainThread) terrain.py:607  Tile removed from (-128, 0)
*(MainThread) terrain.py:568  tile generated at (-512, -128)
*(MainThread) terrain.py:607  Tile removed from (-128, -128)
*(MainThread) terrain.py:568  tile generated at (-512, -256)
*(MainThread) terrain.py:607  Tile removed from (-256, 0)
*(MainThread) terrain.py:607  Tile removed from (-256, -256)
*(MainThread) terrain.py:607  Tile removed from (-256, -128)
*(MainThread) terrain.py:568  tile generated at (-640, -128)
*(MainThread) terrain.py:568  tile generated at (-512, 0)
wwAssertion failed: glyph->_geom_count >= 0 at line 111 of c:\buildslave\release_sdk_win32\build\panda3d\panda\src\text\geomTextGlyph.cxx
Traceback (most recent call last):
  File "C:\src\Panda3D-1.8.0\direct\showbase\ShowBase.py", line 1844, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: glyph->_geom_count >= 0 at line 111 of c:\buildslave\release_sdk_win32\build\panda3d\panda\src\text\geomTextGlyph.cxx
:task(error): Exception occurred in PythonTask igLoop
Traceback (most recent call last):
  File "C:\src\game\src\main.py", line 329, in <module>
    launchTerrainDemo()
  File "C:\src\game\src\main.py", line 326, in launchTerrainDemo
    run()
  File "C:\src\Panda3D-1.8.0\direct\showbase\ShowBase.py", line 2910, in run
    self.taskMgr.run()
  File "C:\src\Panda3D-1.8.0\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\src\Panda3D-1.8.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\src\Panda3D-1.8.0\direct\showbase\ShowBase.py", line 1844, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: glyph->_geom_count >= 0 at line 111 of c:\buildslave\release_sdk_win32\build\panda3d\panda\src\text\geomTextGlyph.cxx
```

**Comment by StephenLujan** [comment]
Wow. I was trying to get the number of geoms down to make it run faster, but I never expected to do so well I would get a negative number of geoms! Just kidding. In all seriousness I've never experienced that issue and I'm not sure how it could have happened. Thanks for the feedback. I'll try to figure out what's going on.
